fullname: alertsnitch

image:
  repository: mikehsu0618/alertsnitch
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9567

env:
  ALERTSNITCH_ADDR: ":9567"
  ALERTSNITCH_DEBUG: "false"
  ALERTSNITCH_BACKEND: "loki"
  ALERTSNITCH_BACKEND_ENDPOINT: "http://loki-gateway.loki"
  ALERTSNITCH_LOKI_TENANT_ID: ""
  ALERTSNITCH_LOKI_TLS_INSECURE_SKIP_VERIFY: "false"
  ALERTSNITCH_LOKI_TLS_CA_CERT_PATH: ""
  ALERTSNITCH_LOKI_TLS_CLIENT_CERT_PATH: ""
  ALERTSNITCH_LOKI_TLS_CLIENT_KEY_PATH: ""

secret:
  create: false
  data:
    ALERTSNITCH_LOKI_BASIC_AUTH_USER: ""
    ALERTSNITCH_LOKI_BASIC_AUTH_PASSWORD: ""
    # TLS sensitive data (if needed)
    # ALERTSNITCH_LOKI_TLS_CA_CERT_PATH: "/path/to/ca-cert.pem"
    # ALERTSNITCH_LOKI_TLS_CLIENT_CERT_PATH: "/path/to/client-cert.pem"
    # ALERTSNITCH_LOKI_TLS_CLIENT_KEY_PATH: "/path/to/client-key.pem"

replicaCount: 1
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  # - host: alertsnitch.local
  #   paths:
  #     - path: /
  #       pathType: Prefix
  tls: []
  #  - secretName: alertsnitch-tls
  #    hosts:
  #      - alertsnitch.local
