{
 "title": "Loki / AlertManager History",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "loki_datasource", "label": "loki_datasource", "query": "loki" },
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 20 triggered Alerts",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, (sum by (alertname) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) + (count by (alertname) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) * 1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triggered Alerts by Severity",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (count_over_time({app=\"alertsnitch\"} |= `` [$__range]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Triggered Alerts by Priority",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(priority) (count_over_time({app=\"alertsnitch\"} |= `` [$__range]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "total number of alert sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"alertsnitch\", alert_status=\"firing\"} [$__range]))"
    }
   ]
  },
  {
   "title": "alert statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({app=\"alertsnitch\", alert_status=\"firing\"} [$__range]))",
     "legendFormat": "{{serverity}}"
    }
   ]
  },
  {
   "title": "total number of alert resolved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=\"alertsnitch\", alert_status=\"resolved\"} [$__range]))"
    }
   ]
  },
  {
   "title": "resolved statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({app=\"alertsnitch\", alert_status=\"resolved\"} [$__range]))",
     "legendFormat": "{{serverity}}"
    }
   ]
  },
  {
   "title": "alert triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(app, severity) (count_over_time({app=\"alertsnitch\", alert_status=\"firing\"} [$__auto]))",
     "legendFormat": "alert triggered count: {{severity}}"
    }
   ]
  },
  {
   "title": "resolved triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(app, severity) (count_over_time({app=\"alertsnitch\", alert_status=\"resolved\"} [$__auto]))",
     "legendFormat": "alert triggered count: {{severity}}"
    }
   ]
  },
  {
   "title": "alert not resolved",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{app=\"alertsnitch\"} | json"
    }
   ]
  },
  {
   "title": "alert resolved",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{app=\"alertsnitch\", alert_status=\"resolved\"} | json"
    }
   ]
  },
  {
   "title": "history alert details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"alertsnitch\"} | json"
    }
   ]
  },
  {
   "title": "MTTR",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app=\"alertsnitch\", alert_status=\"resolved\"} | json"
    }
   ]
  }
 ]
}