adminPassword: admin
adminUser: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: false
        name: Tempo
        type: tempo
        url: http://tempo-gateway.tempo
      - access: proxy
        isDefault: false
        name: Loki
        type: loki
        url: http://loki-gateway.loki

replicas: 1

persistence:
  enabled: true
  size: 1Gi


